spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./db/default
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect