sources:
  garant: "http://rss.garant.ru/news/"
  expert: "https://expert.ru/doc-list/rss/"
  mail: "https://news.mail.ru/rss/90/"
  bbci: "http://feeds.bbci.co.uk/russian/rss.xml"
  duma: "http://duma.gov.ru/news/feed/"
  esquire: "https://esquire.ru/out/feedburner.xml"
  nkj: "https://www.nkj.ru/rss/"
  life: "https://life.ru/xml/feed.xml?hashtag=%D0%BD%D0%BE%D0%B2%D0%BE%D1%81%D1%82%D0%B8"
  popmech: "https://www.popmech.ru/out/public-all.xml"
  cnews: "https://cnews.ru/inc/rss/news.xml"
  astronews: "https://astronews.space/?format=feed&type=rss"
  smart-lab: "https://smart-lab.ru/news/rss/"
  government: "http://government.ru/all/rss/"
  kommersant: "https://www.kommersant.ru/RSS/section-business.xml"
  qq: "https://www.gq.ru/feed/all-content/rss"
  gazeta: "https://www.gazeta.ru/export/rss/first.xml"
  lenta: "https://lenta.ru/rss"
  vedomosti: "https://www.vedomosti.ru/rss/news"
  agroinvestor: "https://www.agroinvestor.ru/feed/public-agronews.xml"
  moex: "https://www.moex.com/export/news.aspx?cat=100"
  russian_rt: "https://russian.rt.com/rss"
  iz: "https://iz.ru/xml/rss/all.xml"
  rbc: "http://static.feed.rbc.ru/rbc/logical/footer/news.rss"
  nasa: "https://www.nasa.gov/rss/dyn/breaking_news.rss"
  news_yandex: "https://news.yandex.ru/cosmos.rss"
  yandex: "https://news.yandex.ru/index.rss"
  rg: "https://rg.ru/tema/ekonomika/rss.xml"
  vesti: "https://www.vesti.ru/vesti.rss"
  forbes: "https://www.forbes.ru/newrss.xml"
  nplus1: "https://nplus1.ru/rss"